# Generated by Django 6.0.1 on 2026-02-08 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=50)),
                ('eage', models.IntegerField()),
                ('eadd', models.IntegerField()),
                ('erank', models.FloatField()),
                ('ecollege', models.CharField(max_length=50)),
                ('ephno', models.IntegerField()),
            ],
        ),
    ]
