# Generated by Django 6.0.1 on 2026-02-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studentdata1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('add', models.CharField(max_length=50)),
                ('gpa', models.FloatField()),
                ('college', models.CharField(max_length=50)),
            ],
        ),
    ]
