# Generated by Django 6.0.2 on 2026-02-10 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='eadd',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='erank',
            field=models.IntegerField(),
        ),
    ]
