# Generated by Django 6.0.2 on 2026-02-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_alter_student_eadd_alter_student_erank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='ephno',
            field=models.CharField(max_length=50),
        ),
    ]
